title = 'Sort Points by Argument'
timelimit = 5.0
forum = "https://github.com/yosupo06/library-checker-problems/issues/248"

[[tests]]
    name = "example.in"
    number = 1
[[tests]]
    name = "random.cpp"
    number = 3
[[tests]]
    name = "max_random.cpp"
    number = 3
[[tests]]
    name = "near_arg.cpp"
    number = 3
[[tests]]
    name = "near_arg_shuffle.cpp"
    number = 3
[[tests]]
    name = "small_all.cpp"
    number = 1
[[tests]]
    name = "only_x_axis.cpp"
    number = 1

[[solutions]]
    name = "wa.cpp"
    wrong = true


[params]
    N_MAX = 200_000
    X_AND_Y_ABS_MAX = 1_000_000_000
